#ifndef BOTCHALLANGE_CONSTANTS_H
#define BOTCHALLANGE_CONSTANTS_H

#define SIZE 10
#define EMPTY 0
#define PONE 1
#define PTWO 2
#define WALL -1

#define TIMELIMIT 0.95

#define INF 1000000

#endif //BOTCHALLANGE_CONSTANTS_H
